/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package short17;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Magi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initializeUI();
    }

    class Book {

        private String name;
        private String icon;
        private String ss;

        Book(String name, String icon, String html) {
            this.name = name;
            this.icon = icon;
            this.ss = html;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getIcon() {
            return icon;
        }

        public void setFlagIcon(String icon) {
            this.icon = icon;
        }

        public String getHtml() {
            return ss;
        }

        public void setHtml(String html) {
            this.ss = html;
        }

    }

    private void initializeUI() {
        setSize(1000, 1000);
        this.setSize(1000, 1000);
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("The Java Series");
        DefaultMutableTreeNode Programmers = new DefaultMutableTreeNode("Books for Java Programmers");
        Book[] books = new Book[]{
            new Book("The Java Tutorial: A Short Course on the Basics", "/2.png", "html/1.html"),
            new Book("The Java Tutorial Continued: The Rest of the JDK", "/2.png", "html/2.html"),
            new Book("The JFC Swing Tutorial: A Guide to Constructing GUIs", "/2.png", "html/3.html"),
            new Book("Effective Java Programming Language Guide", "/1.png", "html/4.html"),
            new Book("The Java Programming Language", "/1.png", "html/5.html"),
            new Book("The Java Developers Almanac", "/1.png", "html/6.html"),};

        for (Book book : books) {
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(book.name.toString());
            Programmers.add(node);
        }

        DefaultMutableTreeNode Implementers = new DefaultMutableTreeNode("Books for Java Implementers");
        books = new Book[]{
            new Book("The Java Virtual Machine Specification", "/1.png", "html/7.html"),
            new Book("The Java Language Specification", "/1.png", "html/8.html")
        };

        for (Book book : books) {
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(book.name.toString());
            Implementers.add(node);
        }

        root.add(Programmers);
        root.add(Implementers);
        DefaultTreeModel data = new DefaultTreeModel(root);
        this.tree.setModel(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree.setPreferredSize(new java.awt.Dimension(200, 16));
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tree);

        jSplitPane1.setTopComponent(jScrollPane2);

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        jSplitPane1.setRightComponent(jScrollPane1);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked

    }//GEN-LAST:event_treeMouseClicked

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        //TODO

    }//GEN-LAST:event_treeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea text;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
