/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import javax.swing.JColorChooser;

/**
 *
 * @author Magi
 */
public class DrawText extends javax.swing.JFrame {

    /**
     * Creates new form DrawText
     */
    Graphics g = null;
    Color color = null;
    Font font = null;
    int fontStyle = Font.PLAIN;
    int fontSize = 15;
    String fontName = Font.SANS_SERIF;
    String drawnText = "";

    public DrawText() {
        initComponents();
        loadFonts();
        g = this.pDraw.getGraphics();
        color = Color.BLACK;
        g.setColor(color);
        font = new Font(fontName, fontStyle, fontSize);
        this.showFontProperties();
    }

    private void loadFonts() {
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = env.getAllFonts();
        this.cbFont.removeAllItems();
        String fName;
        for (Font f : fonts) {
            fName = f.getFontName();
            this.cbFont.addItem(fName);
        }
    }

    private void showFontProperties() {
        txtProperties.setText("");
        txtProperties.append("Family: " + font.getFamily() + "\n");
        txtProperties.append("Name: " + font.getName() + "\n");
        txtProperties.append("Style: " + font.getStyle() + "\n");
        txtProperties.append("Size: " + font.getSize() + "\n");
        if (g != null) {
            FontMetrics fm = g.getFontMetrics();
            txtProperties.append("\nFont mretics:\n");
            txtProperties.append("Ascent: " + fm.getAscent() + "\n");
            txtProperties.append("Max. Ascent: " + fm.getMaxAscent() + "\n");
            txtProperties.append("Descent: " + fm.getDescent() + "\n");
            txtProperties.append("Leading: " + fm.getLeading() + "\n");
            txtProperties.append("Height: " + fm.getHeight() + "\n");
            txtProperties.append("Max. advance: " + fm.getMaxAdvance() + "\n");
            if (drawnText.length() > 0) {
                txtProperties.append("String width: " + fm.stringWidth(drawnText) + "\n");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pControl = new javax.swing.JPanel();
        lbColor = new javax.swing.JLabel();
        btnColor = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        cbFont = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbFontStyle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProperties = new javax.swing.JTextArea();
        pDraw = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pControl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N
        pControl.setPreferredSize(new java.awt.Dimension(622, 100));

        lbColor.setBackground(new java.awt.Color(0, 0, 0));
        lbColor.setText("Color");
        lbColor.setName("lbColor"); // NOI18N
        lbColor.setOpaque(true);
        pControl.add(lbColor);

        btnColor.setText("Choose Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        pControl.add(btnColor);

        jLabel2.setText("Font:");
        pControl.add(jLabel2);

        cbFont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFontActionPerformed(evt);
            }
        });
        pControl.add(cbFont);

        jLabel3.setText("Size: ");
        pControl.add(jLabel3);

        txtSize.setPreferredSize(new java.awt.Dimension(45, 25));
        txtSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSizeFocusLost(evt);
            }
        });
        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });
        pControl.add(txtSize);

        jLabel4.setText("Style");
        pControl.add(jLabel4);

        cbFontStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLD", "ITALIC", "PLAIN" }));
        cbFontStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFontStyleActionPerformed(evt);
            }
        });
        pControl.add(cbFontStyle);

        jLabel5.setText("Draw Text");
        pControl.add(jLabel5);

        txt1.setPreferredSize(new java.awt.Dimension(150, 25));
        pControl.add(txt1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Font Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        txtProperties.setColumns(20);
        txtProperties.setRows(5);
        jScrollPane1.setViewportView(txtProperties);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pDraw.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Click Mouse To Draw Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        pDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pDrawMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pDrawLayout = new org.jdesktop.layout.GroupLayout(pDraw);
        pDraw.setLayout(pDrawLayout);
        pDrawLayout.setHorizontalGroup(
            pDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        pDrawLayout.setVerticalGroup(
            pDrawLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pControl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(pDraw, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(pControl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .add(pDraw, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Choose a color", color);
        if (newColor != null) {
            color = newColor;
        }
        lbColor.setBackground(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void cbFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFontActionPerformed
        this.fontName = ((String) cbFont.getSelectedItem());
        font = new Font(fontName, fontStyle, fontSize);
        this.showFontProperties();
    }//GEN-LAST:event_cbFontActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        fontSize = Integer.parseInt(txtSize.getText());
        font = new Font(fontName, fontStyle, fontSize);
        g.setFont(font);
        this.showFontProperties();
    }//GEN-LAST:event_txtSizeActionPerformed

    private void cbFontStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFontStyleActionPerformed
        String str = (String) (cbFontStyle.getSelectedItem());
        if (str.equalsIgnoreCase("Bold")) {
            fontStyle = Font.BOLD;
        } else if (str.equalsIgnoreCase("Italic")) {
            fontStyle = Font.ITALIC;
        } else {
            fontStyle = Font.PLAIN;
        }
        font = new Font(fontName, fontStyle, fontSize);
        this.showFontProperties();
    }//GEN-LAST:event_cbFontStyleActionPerformed

    private void txtSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSizeFocusLost
        fontSize = Integer.parseInt(txtSize.getText());
        font = new Font(fontName, fontStyle, fontSize);
        g.setFont(font);
        this.showFontProperties();
    }//GEN-LAST:event_txtSizeFocusLost

    private void pDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDrawMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        g.setFont(font);
        g.setColor(color);
        drawnText = txt1.getText();
        g.drawString(drawnText, x, y);
        showFontProperties();
    }//GEN-LAST:event_pDrawMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnColor;
    private javax.swing.JComboBox<String> cbFont;
    private javax.swing.JComboBox<String> cbFontStyle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbColor;
    private javax.swing.JPanel pControl;
    private javax.swing.JPanel pDraw;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextArea txtProperties;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
