/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Student;
import model.StudentDAO;
import rmi.IStudentDAO;

/**
 *
 * @author DAI PHUC
 */
public class Student_GUI extends javax.swing.JFrame
{

    /**
     * Creates new form Student_GUI
     */
    StudentDAO stdDB = new StudentDAO();

    Thread1 t1 = new Thread1("Thread1");
    Thread2 t2 = new Thread2("Thread2");
    public Student_GUI()
    {
        initComponents();
        t1.start();
        t2.start();
    }

    private class Thread1 extends Thread
    {

        public Thread1(String name)
        {
            this.setName(name);
        }

        @Override
        public void run()
        {
            this.countDown();
        }

        public void countDown()
        {
            int i = 1;
            while (i <= 100)
            {
                lbCount1.setText("Remaining " + i + " seconds");
                try
                {
                    i++;
                    if (i == 100)
                    {
                        int ret = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit", "Confirm", JOptionPane.YES_NO_OPTION);
                        if (ret == JOptionPane.YES_OPTION)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Goodbye");
                            System.exit(1);
                        } else
                        {
                            i = 1;
                        }
                    }
                    Thread.sleep(500);
                } catch (InterruptedException e)
                {
                    System.out.println(e);
                }
            }
        }
    }
    
    private class Thread2 extends Thread
    {

        public Thread2(String name)
        {
            this.setName(name);
        }

        @Override
        public void run()
        {
            this.countDown();
        }

        public void countDown()
        {
            int i = 200;
            while (i >= 100)
            {
                lbCount2.setText("Remaining " + i + " seconds");
                try
                {
                    i--;
                    if (i == 100)
                    {
                        int ret = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit", "Confirm", JOptionPane.YES_NO_OPTION);
                        if (ret == JOptionPane.YES_OPTION)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Goodbye");
                            System.exit(1);
                        } else
                        {
                            i = 200;
                        }
                    }
                    Thread.sleep(500);
                } catch (InterruptedException e)
                {
                    System.out.println(e);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        btnNew = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        PaneCheck = new javax.swing.JPanel();
        lbCount1 = new javax.swing.JLabel();
        lbCount2 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jTextField6.setText("jTextField6");

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStudent);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("SudentID:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("Last_Name:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setText("First_Name:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setText("Phone:");

        txtLastName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtLastNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMale);
        rdMale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        rdMale.setText("Male");

        buttonGroup1.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        rdFemale.setText("Female");

        btnNew.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewActionPerformed(evt);
            }
        });

        btnShow.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnShow)
                        .addGap(108, 108, 108)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdMale)
                        .addGap(45, 45, 45)
                        .addComponent(rdFemale))
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFirstName, txtLastName, txtPhone, txtStudentId});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNew, btnShow});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdMale)
                    .addComponent(rdFemale))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnShow))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, txtFirstName, txtLastName, txtPhone, txtStudentId});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNew, btnShow});

        lbCount1.setText("Time Remaining");

        lbCount2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCount2.setText("Time Remaining");

        javax.swing.GroupLayout PaneCheckLayout = new javax.swing.GroupLayout(PaneCheck);
        PaneCheck.setLayout(PaneCheckLayout);
        PaneCheckLayout.setHorizontalGroup(
            PaneCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneCheckLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lbCount2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        PaneCheckLayout.setVerticalGroup(
            PaneCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneCheckLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PaneCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCount2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PaneCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PaneCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtLastNameActionPerformed
    {//GEN-HEADEREND:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNewActionPerformed
    {//GEN-HEADEREND:event_btnNewActionPerformed
        // TODO add your handling code here:
        if (valid())
        {
            String studentID = this.txtStudentId.getText();
            String lastName = this.txtLastName.getText();
            String firstName = this.txtFirstName.getText();
            String gender = this.buttonGroup1.getSelection().toString().equalsIgnoreCase("Male")?"M":"F";
            String phone = this.txtPhone.getText();
            Student stu = stdDB.getStudent(studentID);
            if (stu == null)
            {
                int check = stdDB.addStudent(studentID, lastName, firstName, gender, Integer.parseInt(phone));
                if (check != 0)
                {
                    JOptionPane.showMessageDialog(this, "Add Student successfully!");
                } else
                {
                    JOptionPane.showMessageDialog(this, "Add Student failed!");
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "Duplicate key!");
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnShowActionPerformed
    {//GEN-HEADEREND:event_btnShowActionPerformed
        // TODO add your handling code here:
        try
        {
            // TODO add your handling code here:
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("StudentID");
            model.addColumn("LastName");
            model.addColumn("FirstName");
            model.addColumn("Gender");
            model.addColumn("Phone");
            IStudentDAO studentDAO = (IStudentDAO) Naming.lookup("rmi://localhost:1500/StudentDAO");
            ArrayList<Student> studentList = studentDAO.getList();
            for (Student student : studentList)
            {
                model.addRow(student.toArray());
            }
            tblStudent.setModel(model);
        } catch (NotBoundException ex)
        {
            Logger.getLogger(Student_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex)
        {
            Logger.getLogger(Student_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex)
        {
            Logger.getLogger(Student_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnShowActionPerformed

    public boolean valid()
    {
        String S;
        S = this.txtStudentId.getText().trim().toUpperCase();
        this.txtStudentId.setText(S);
        if (!S.matches("^DE\\d{6}$"))
        {
            JOptionPane.showMessageDialog(this, "Student ID must be in format DE + 6 digits");
            txtStudentId.requestFocus();
            return false;
        }

        if (stdDB.getStudent(S) != null)
        {
            JOptionPane.showMessageDialog(this, "This Student ID existed");
            txtStudentId.requestFocus();
            return false;
        }

        S = this.txtLastName.getText().trim().toUpperCase();
        this.txtLastName.setText(S);
        if (S.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Last name is not empty");
            txtLastName.requestFocus();
            return false;
        }

        S = this.txtFirstName.getText().trim().toUpperCase();
        this.txtFirstName.setText(S);
        if (S.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "First name is not empty");
            txtFirstName.requestFocus();
            return false;
        }

        S = this.txtPhone.getText().trim().toUpperCase();
        this.txtPhone.setText(S);
        if (!S.matches("^0\\d{9}$"))
        {
            JOptionPane.showMessageDialog(this, "Please input Phone in format 0123456789");
            txtPhone.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Student_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Student_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Student_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Student_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Student_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneCheck;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbCount1;
    private javax.swing.JLabel lbCount2;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
